import type { Metadata } from "next";
import {GoogleOAuthProvider} from '@react-oauth/google'
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <GoogleOAuthProvider clientId="516607384733-101193hvvoqsaua0kni4e7uj62o36cr9.apps.googleusercontent.com">
      {children}
      </GoogleOAuthProvider>
       
      </body>
    </html>
  );
}
